version: '3.9'

services:
    api:
        restart: on-failure
        build: ./
        image: madralo-api
        depends_on:
            - postgres
        ports:
            - '8080:8080'
        volumes:
            - ./:/app/

    postgres:
        container_name: postgres
        image: postgres:latest
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_DB=${PG_DB}

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
            - 5050:80
        depends_on:
            - postgres
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        environment:
            - PGADMIN_LISTEN_ADDRESS=${PGADMIN_LISTEN}
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}

volumes:
    postgres-data:
        driver: local
    pgadmin-data:
        driver: local
