version: '3.9'

services:
    api:
        restart: on-failure
        build: ./
        image: madralo-api
        depends_on:
            - postgres
        ports:
            - '8080:8080'
        volumes:
            - ./:/app/

    postgres:
        container_name: postgres
        image: postgres:latest
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=madralo

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
            - 5050:80
        depends_on:
            - postgres
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        environment:
            - PGADMIN_LISTEN_ADDRESS=0.0.0.0
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin

volumes:
    postgres-data:
        driver: local
    pgadmin-data:
        driver: local
