version: '3.9'

services:
    api:
        restart: on-failure
        image: node:lts-alpine
        working_dir: /app
        command: npm run start.dev
        depends_on:
            - postgres
        ports:
            - 8080:8080
        volumes:
            - ./:/app

    postgres:
        container_name: ${PG_HOST}
        image: postgres:latest
        ports:
            - '${PG_PORT}:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_DB=${PG_DB}

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
            - 5050:80
        depends_on:
            - postgres
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        environment:
            - PGADMIN_LISTEN_ADDRESS=${PGADMIN_LISTEN}
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}

volumes:
    postgres-data:
        driver: local
    pgadmin-data:
        driver: local
